#!/usr/intel/pkgs/perl/5.8.5/bin/perl

use strict;
use warnings;
use File::Path;
use Cwd;

my $vim_hg_path = 'vim.latest';
my $vim_latest_tarname = 'vim.latest.tar.bz2';
my $vim_7p4_tarname = 'vim-7.4.tar.bz2';
my $working_directory = getcwd();

#--------------------------------------------------------------
# if hg clone directory exists then just update the clone
# otherwise create a fresh clone and update it
#--------------------------------------------------------------
mkpath($vim_hg_path);  # same as mkdir -p
if (-d "$vim_hg_path/.hg") {
  print "Updating vim clone ... \n";
  chdir $vim_hg_path;
  print `hg update -C` . "\n";
  chdir $working_directory;
} else {
  print "Creating vim clone (have patience, it will take several minutes) ... \n";
  rmtree $vim_hg_path;
  print `env http_proxy=http://proxy.fm.intel.com:911 hg clone http://vim.googlecode.com/hg/ vim.latest` . "\n";
}
print "Zipping vim.latest.tar.bz2 file ...\n"; 
if (-f $vim_latest_tarname) {
  rmtree $vim_latest_tarname;
}
`tar --exclude-vcs -jcvf $vim_latest_tarname $vim_hg_path/`;
if (! -f $vim_latest_tarname) {
  print "zipping $vim_latest_tarname failed ...\n";
  exit 1;
}

#--------------------------------------------------------------
# download the frozen 7.4 version of the code 
#--------------------------------------------------------------
print "\nDownloading $vim_7p4_tarname file\n\n";
if (-f $vim_7p4_tarname) {
  rmtree $vim_7p4_tarname;
}
`env ftp_proxy=http://proxy.fm.intel.com:911 wget ftp://ftp.vim.org/pub/vim/unix/$vim_7p4_tarname`;
if (! -f $vim_7p4_tarname) {
  print "downloading $vim_7p4_tarname failed ...\n";
  exit 1;
}

exit 0;
